### ISSUE TITLE
Birdseye View

### ISSUE THREAD

**Issue by alexdingis** [digidem/leaflet-bing-layer#2]
Is 'birdseye' view an acceptable input instead of 'aerial', 'aerial with labels' or 'road'?

**Comment by gmaclennan** [comment]
Just looked into this. It is not working because [according to the docs](https://msdn.microsoft.com/en-us/library/ff701716.aspx) requests for metadata for `Birdseye` layers need a center-point. The code needs updating to make multiple metadata requests as the map moves. Will take a look at this in the next couple of weeks, unless anyone else feels like having a go and submitting a pull request :)

**Comment by gmaclennan** [comment]
According to [this Microsoft post](https://social.msdn.microsoft.com/Forums/en-US/3d80d4a6-f4c9-4926-a336-e0d545b1ef3c/is-it-possible-to-retrieve-birdseye-map-tiles-using-rest-services?forum=bingmapsservices) Birdseye imagery is not available through REST services because of licensing issues, so unfortunately neither `BirdseyeWithLabels` nor `Birdseye` will work. I will update the docs.
